const layoutsData = [
  { name: '',
    uri: require('../images/templates/hero-card-template.jpg'),
    keywords: [],
  },
  { name: '',
    uri: require('../images/templates/grid-desc-template.jpg'),
    keywords: [],
  },
  { name: '',
    uri: require('../images/templates/portfolio1-template.jpg'),
    keywords: [],
  },
  { name: '',
    uri: require('../images/templates/description2-template.jpg'),
    keywords: [],
  },
  { name: '',
    uri: require('../images/templates/bar-template.jpg'),
    keywords: [],
  },
  { name: '',
    uri: require('../images/templates/grid-pricing-template.jpg'),
    keywords: [],
  },
  // { name: '',
  //   uri: require('../images/templates/photo-desc-template.jpg'),
  //   keywords: [],
  // },
  // { name: '',
  //   uri: require('../images/templates/photography2-template.jpg'),
  //   keywords: [], 
  // },
  { name: '',
    uri: require('../images/templates/bright-template.jpg'),
    keywords: [],
  },
  { name: '',
    uri: require('../images/templates/pricing-template.jpg'),
    keywords: [],
  },
  { name: '',
    uri: require('../images/templates/grid3-template.jpg'),
    keywords: [],
  },
  { name: '',
    uri: require('../images/templates/hero3-template.png'),
    keywords: [],
  },
  { name: '',
    uri: require('../images/templates/grid2-template.jpg'),
    keywords: [],
  },
  { name: '',
    uri: require('../images/templates/hero2-template.jpg'),
    keywords: [],
  },
  { name: '',
    uri: require('../images/templates/green-template.jpg'),
    keywords: [],
  },
  { name: '',
    uri: require('../images/templates/pricing-template.png'),
    keywords: [],
  },
  { name: '',
    uri: require('../images/templates/art-template.jpg'),
    keywords: [],
  },
  { name: '',
    uri: require('../images/templates/photography-template.jpg'),
    keywords: [],
  },
  { name: '',
    uri: require('../images/templates/restaurant-template.jpg'),
    keywords: [],
  },
];

export default layoutsData;