const layoutsData = [
  { uri: require('../images/templates/portfolio-template.jpg'),
    layouts: ['grid'],
  },
  { uri: require('../images/templates/spotify-template.png'),
    layouts: ['hero'],
  },
  { uri: require('../images/templates/contact-template.png'),
    layouts: ['contact'],
  },
  { uri: require('../images/templates/hero-card-template.jpg'),
    layouts: ['hero', 'caption'],
  },
  { uri: require('../images/templates/grid-desc-template.jpg'),
    layouts: ['hero', 'grid', 'caption'],
  },
  { uri: require('../images/templates/portfolio1-template.jpg'),
    layouts: ['portfolio', 'grid'],
  },
  { uri: require('../images/templates/description2-template.jpg'),
    layouts: ['grid', 'description'],
  },
  { uri: require('../images/templates/bar-template.jpg'),
    layouts: ['hero'],
  },
  { uri: require('../images/templates/grid-pricing-template.jpg'),
    layouts: ['grid', 'pricing'],
  },
  { uri: require('../images/templates/bright-template.jpg'),
    layouts: ['hero'],
  },
  { uri: require('../images/templates/grid3-template.jpg'),
    layouts: ['grid'],
  },
  { uri: require('../images/templates/hero3-template.png'),
    layouts: ['hero'],
  },
  { uri: require('../images/templates/grid2-template.jpg'),
    layouts: ['grid'],
  },
  { uri: require('../images/templates/hero2-template.jpg'),
    layouts: ['hero'],
  },
  { uri: require('../images/templates/green-template.jpg'),
    layouts: ['hero'],
  },
  { uri: require('../images/templates/pricing-template.png'),
    layouts: ['pricing'],
  },
  { uri: require('../images/templates/art-template.jpg'),
    layouts: ['hero'],
  },
  { uri: require('../images/templates/photography-template.jpg'),
    layouts: ['hero'],
  },
  { uri: require('../images/templates/hero-template.png'),
    layouts: ['hero'],
  },
  { uri: require('../images/templates/restaurant-template.jpg'),
    layouts: ['hero', 'restaurant'],
  },
];

export default layoutsData;