const layoutsData = [
  { uri: require('../../../images/templates/portfolio-template.jpg'),
    layouts: ['PinterestContent'],
  },
  { uri: require('../../../images/templates/spotify-template.png'),
    layouts: ['GradientHero'],
  },
  { uri: require('../../../images/templates/contact-template.png'),
    layouts: ['ImageCaption'],
  },
  { uri: require('../../../images/templates/hero-card-template.jpg'),
    layouts: ['ImageContent'],
  },
  { uri: require('../../../images/templates/grid-desc-template.jpg'),
    layouts: ['ImageContent'],
  },
  { uri: require('../../../images/templates/portfolio1-template.jpg'),
    layouts: ['PinterestContent'],
  },
  { uri: require('../../../images/templates/description2-template.jpg'),
    layouts: ['PinterestContent', 'ImageCaption'],
  },
  { uri: require('../../../images/templates/bar-template.jpg'),
    layouts: ['ImageHero'],
  },
  { uri: require('../../../images/templates/grid-pricing-template.jpg'),
    layouts: ['PinterestContent'],
  },
  { uri: require('../../../images/templates/bright-template.jpg'),
    layouts: ['PinterestContent', 'GradientHero'],
  },
  { uri: require('../../../images/templates/grid3-template.jpg'),
    layouts: ['PinterestContent', 'ImageHero'],
  },
  { uri: require('../../../images/templates/hero3-template.png'),
    layouts: ['ImageContent'],
  },
  { uri: require('../../../images/templates/grid2-template.jpg'),
    layouts: ['PinterestContent'],
  },
  { uri: require('../../../images/templates/hero2-template.jpg'),
    layouts: ['PinterestText', 'ImageHero'],
  },
  { uri: require('../../../images/templates/green-template.jpg'),
    layouts: ['ImageContent', 'ImageHero'],
  },
  { uri: require('../../../images/templates/pricing-template.png'),
    layouts: ['PinterestContent'],
  },
  { uri: require('../../../images/templates/art-template.jpg'),
    layouts: ['ImageContent', 'PinterestText'],
  },
  { uri: require('../../../images/templates/photography-template.jpg'),
    layouts: ['ImageCaption', 'ImageHero'],
  },
  { uri: require('../../../images/templates/hero-template.png'),
    layouts: ['ImageCaption'],
  },
  { uri: require('../../../images/templates/restaurant-template.jpg'),
    layouts: ['ImageHero'],
  },
  { uri: require('../../../images/templates/thats-all.png'),
  },
];

export default layoutsData;